name: overseer # define the name of the app

services: # define services
  app: # main Python app
    build: ./ # build using a Dockerfile in the local directory
    depends_on: # delay startup until the DB is ready to accept connections
      db:
        condition: service_healthy
    restart: always # if errors occur, restart
    env_file:
      - path: "./conf/bot-config.env"
    environment: # pass location of db to the container
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: overseer
      POSTGRES_USER: overseer
      POSTGRES_PASSWORD: overseer
    networks: # allow the two containers to communicate
      - db

  db: # postgres DB
    hostname: db # assign a hostname for easier connection
    image: postgres:18.6-alpine3.23 # use the latest Postgres Alpine image
    shm_size: 128mb # define a memory limit
    restart: always # restart if errors occur
    environment:
      POSTGRES_DB: overseer
      POSTGRES_USER: overseer
      POSTGRES_PASSWORD: overseer
    volumes: # map a volume to the Postgres data directory
      - db-data:/var/lib/postgresql # data
      - ./sql:/docker-entrypoint-initdb.d # initialization scripts
    networks: # allow the two containers to communicate
      - db
    healthcheck: # set up a health check to confirm when the DB is ready
      test: ["CMD-SHELL", "pg_isready -U overseer"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes: # allow Docker to handle volume storage
  db-data:

networks: # allow Docker to handle networking
  db:
